from __future__ import annotations

from typing import Any, Protocol

from calendar_pilot.types import AuthorityGrant, CandidateCalendarAction, RawCalendarObservation, RewardEvent, UserBiography


class TraceSink(Protocol):
    def emit(
        self,
        *,
        obj: str,
        stage: str,
        status: str,
        trace_id: str,
        payload: dict[str, Any] | None = None,
        causal_parent_id: str | None = None,
    ) -> None: ...


class ConversationRouterProtocol(Protocol):
    def route(self, turn_text: str, *, context: dict[str, Any]) -> Any: ...


class FrontierServiceProtocol(Protocol):
    def generate(self, goal: str, observation: RawCalendarObservation, biography: UserBiography, *, trace_id: str) -> Any: ...


class ActionLifecycleProtocol(Protocol):
    def prepare(self, candidate: CandidateCalendarAction, observation: RawCalendarObservation, grant: AuthorityGrant | str | None, *, trace_id: str) -> Any: ...
    def simulate(self, envelope: Any) -> Any: ...
    def stage(self, envelope: Any) -> Any: ...
    def commit(self, envelope: Any, *, confirmed: bool) -> Any: ...
    def verify(self, envelope: Any) -> Any: ...
    def reward(self, envelope: Any, event: RewardEvent) -> Any: ...
    def undo(self, rollback_handle_id: str, grant: AuthorityGrant | str | None, *, trace_id: str) -> Any: ...


class ReplayJournalProtocol(Protocol):
    def append(self, record_type: str, payload: dict[str, Any], *, trace_id: str, causal_parent_id: str | None = None) -> str: ...
    def causal_chain(self, trace_id: str) -> list[dict[str, Any]]: ...
    def export(self) -> dict[str, Any]: ...


class FrontendProjectorProtocol(Protocol):
    def view(self) -> dict[str, Any]: ...
